otel:
  instrumentation:
    logback-appender:
      experimental:
        capture-code-attributes: true
  propagators:
    - b3
  resource:
    attributes:
      attributeFromYaml: true # boolean will be automatically converted to string by spring
